### ISSUE TITLE
возможно отсутствует файл модели в поставке модуля

### ISSUE THREAD

**Issue by iachaly** [aTastyCookie/yandex_opencart2#1]
Работаю с opencart 2.0.1.1, возникла задача подключить оплату p2p.
Выкачал предлагаемое расширение. 
Сконфигурировал по инструкции. Увидел ошибку ![2015-02-16_023256](https://cloud.githubusercontent.com/assets/11027676/6210312/ba508ab4-b5e7-11e4-9466-611dd442eb59.jpg)
Предположения:
1. Где-то сам недоглядел, подскажите пожалуйста.
2. Отсутствует файл модели в поставке модуля.

**Comment by ded100let** [comment]
Привет! Я автор. Проблема в разных слешах. Пожалуйста тестируйте на нормальном вебхостинге. есть и бесплатные.

**Comment by ded100let** [comment]
Посмотрите https://oc.devpresta.ru/
Всё в порядке.

**Comment by ded100let** [comment]
К томуже локально вы не сможете провести все тесты.

**Comment by iachaly** [comment]
Я сожалею, но вы не правы. Данная ошибка повторяется минимум на двух хостингах и в рамках windows openserver. Если не получается разобраться, скиньте мне пожалуйста дамп вашего демо-сайта, найду и скажу в каком месте у вас ошибка.

**Comment by ded100let** [comment]
У меня на демо linux. на win не проверял, файл-есть всё на месте. дамп вам не к чему. этот модуль (на этом гите прекращается поддержка.) скоро будет на официальном. обновлённая версия. я напишу когда. Если знаете где ошибка - буду рад услышать.

**Comment by iachaly** [comment]
Я тогда на домашней винде развернул для чистоты эксперимента, чтобы окончательно удостовериться. Вот на линуксе. Notice: Error: Could not load model /home/catalog/model/payment/yamodule.php! in /home/vqmod/vqcache/vq2-system_engine_loader.php on line 24
Может быть тогда скинете именно файл /catalog/model/payment/yamodule.php ?
Ошибка в том, что не все файлы предоставлены на гите, и если вы не можете найти какой это файл, это можно сделать скинув дамп вашей демки. Разверну, посмотрю, не бойтесь, это же демо! Либо пришлите yamodule.php - мне кажется что не хватает только его.

На всякий случай лог действий.
Заливаем на ос2011 модуль. активация пака, активация оплаты (настройки оплаты отсутствуют), идём в настройки пака, вкладка p2p заполняем "Активность Номер вашего кошелька yandex деньги Id приложения Секретный Вести журнал логов" остальное не трогаем, остальные вкладки не трогаем. сохраняем. Проверяем на заказе - вышеуказанная ошибка.

**Comment by ded100let** [comment]
добавь меня в скайп d-link570
